var rule = {
  title: '爱欧乐影院',
  host: 'https://www.iole.app/',
  url: '/vodshow/fyclass--------fypage---.html',
  searchUrl: '/vodsearch/page/fypage/wd/*.html',
  class_parse: '.top_nav li;a&&Text;a&&href;.*/(.*?).html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  play_parse: true,
  lazy: '',
  limit: 6,
  推荐: '.cbox_list;*;*;*;*;*',
  double: true,
  一级: 'ul.vodlist li;a&&title;a&&data-original;.pic_text&&Text;a&&href',
  二级: {
    title: 'h2&&Text',
    img: '.vodlist_thumb&&data-original',
    desc: 'ul&&li:eq(1)&&Text;ul&&li:eq(2)&&Text;ul&&li:eq(3)&&Text',
    content: '.content_desc&&Text',
    tabs: '.play_source_tab&&a',
    lists: '.content_playlist:eq(#id) li',
  },
  搜索: '*',
}
