var rule = {
  title: '爱欧乐影院',
  host: 'https://www.iole.app/',
  url: '/vodshow/fyclass--------fypage---.html',
  searchUrl: '/vodsearch/page/fypage/wd/*.html',
  class_parse: '.top_nav li;a&&Text;a&&href;.*/(.*?).html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  play_parse: true,
  lazy: '',
  limit: 6,
  推荐: '.cbox_list;*;*;*;*;*',
  double: true,
  一级: '.top_nav li:lt(6);a&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.detail_title&&Text',
    img: '.lazy&&data-original',
    desc: 'p.data&&Text;.detail_imform&&p:eq(1)&&Text',
    content: '.detail_content&&Text',
    tabs: '.play_source_tab&&a',
    lists: '.content_playlist:eq(#id) li',
  },
  搜索: '*',
}
